// <auto-generated />
namespace BITCollege_MG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_next_unique_number_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_next_unique_number_class));
        
        string IMigrationMetadata.Id
        {
            get { return "202102090241449_added_next_unique_number_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
