// <auto-generated />
namespace BITCollege_MG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class applied_number_automation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applied_number_automation));
        
        string IMigrationMetadata.Id
        {
            get { return "202102091514236_applied_number_automation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
